import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Header/Navbar";
import Container from "@/Components/Container/Container";
import Footer from "@/Components/Footer/Footer";
import AuthProvider from "@/provider/AuthProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: " Next Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>

            <Container>
            <Navbar></Navbar>

              {children}
              <Footer></Footer>
            </Container>

        </AuthProvider>
      </body>
    </html>
  )
}
